Presentations/Atilim.Presentations.WebApplication/ViewModels/StudentViewModels/CreateStudentViewModel.cs
namespace Atilim.Presentations.WebApplication.ViewModels.StudentViewModels
{
    public class CreateStudentViewModel
    {
        public int StudentNo { get; set; }

        public StudentIdentityViewModel StudentItentity { get; set; }

        public ContactInformationViewModel ContactInformation { get; set; }
    }
}

Presentations/Atilim.Presentations.WebApplication/ViewModels/StudentViewModels/StudentViewModel.cs
using Atilim.Presentations.WebApplication.ViewModels.CurriculumViewModels;

namespace Atilim.Presentations.WebApplication.ViewModels.StudentViewModels
{
    public class StudentViewModel
    {
        public int Id { get; set; }
        public int StudentNo { get; set; }
        public string FullName { get; set; }
        public int CurriculumId { get; set; }

        public CurriculumWithLessonViewModel Curriculum { get; set; }

        public StudentIdentityViewModel StudentIdentity { get; set; }

        public ContactInformationViewModel ContactInformation { get; set; }
    }
}

Presentations/Atilim.Presentations.WebApplication/Controllers/CurriculumsController.cs
using Atilim.Presentations.WebApplication.Services.Interfaces;
using Atilim.Presentations.WebApplication.ViewModels.CurriculumViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Atilim.Presentations.WebApplication.Controllers
{
    [Authorize(Roles = "admin")]
    public class CurriculumsController : Controller
    {
        private readonly ICurriculumService _curriculumService;
        private readonly ILessonService _lessonService;

        public CurriculumsController(ICurriculumService curriculumService, ILessonService lessonService)
        {
            _curriculumService = curriculumService;
            _lessonService = lessonService;
        }

        public async Task<IActionResult> Index()
        {
            var curriculums = await _curriculumService.GetCurriculumWithLessonsAsync();

            return View(curriculums);
        }

        public async Task<IActionResult> GetLessonsByCurriculumId(int curriculumId)
        {
            var result = await _curriculumService.GetCurriculumWithLessonsByIdAsync(curriculumId);

            return PartialView(result);
        }


        public async Task<IActionResult> Insert()
        {
            var lessons = await _lessonService.GetAll();

            var curriculumLessons = lessons.Select(l => new CurriculumLessonViewModel
            {
                LessonId = l.Id,
                Lesson = l,
            }).ToList();

            var result = new CurriculumWithLessonViewModel()
            {
                CurriculumLessons = curriculumLessons,
            };

            return View(result);
        }

        [HttpPost]
        public async Task<IActionResult> Insert(CurriculumWithLessonViewModel curriculumWithLessonViewModel)
        {
            var lessons = await _lessonService.GetAll();

            curriculumWithLessonViewModel.CurriculumLessons = lessons.Where(l => curriculumWithLessonViewModel.SelectedCurriculumLessons.Contains(l.Id))
                                                                     .Select(l => new CurriculumLessonViewModel
                                                                     {
                                                                         LessonId = l.Id,
                                                                         Lesson = l,
                                                                     })
                                                                     .ToList();

            var result = await _curriculumService.InsertAsync(curriculumWithLessonViewModel);

            return RedirectToAction(nameof(Index));
        }


        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var result = await _curriculumService.GetByIdAsync(id);

            result.Lessons = await _lessonService.GetAll();

            result.SelectedCurriculumLessons = result.CurriculumLessons.Select(cl => cl.LessonId).ToList();

            return View(result);
        }

        [HttpPost]
        public async Task<IActionResult> Update(CurriculumWithLessonViewModel curriculumWithLessonViewModel)
        {

            var lessons = await _lessonService.GetAll();

            curriculumWithLessonViewModel.CurriculumLessons = lessons.Where(l => curriculumWithLessonViewModel.SelectedCurriculumLessons.Contains(l.Id))
                                                                    .Select(l => new CurriculumLessonViewModel
                                                                    {
                                                                        LessonId = l.Id,
                                                                        Lesson = l,
                                                                    })
                                                                    .ToList();

            var result = await _curriculumService.UpdateAsync(curriculumWithLessonViewModel);

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            var result = await _curriculumService.DeleteAsync(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

Presentations/Atilim.Presentations.WebApplication/Controllers/StudentsController.cs
using Atilim.Presentations.WebApplication.Services.Interfaces;
using Atilim.Presentations.WebApplication.ViewModels.StudentViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Atilim.Presentations.WebApplication.Controllers
{
    [Authorize(Roles = "admin")]
    public class StudentsController : Controller
    {
        private readonly IStudentService _studentService;

        public StudentsController(IStudentService studentService)
        {
            _studentService = studentService;
        }

        public async Task<IActionResult> Index()
        {
            var students = await _studentService.GetAllAsync();

            return View(students);
        }

        public async Task<IActionResult> GetStudentOtherInfosById(int studentId)
        {
            var student = await _studentService.GetByIdAsync(studentId);

            return PartialView(student);
        }

        public async Task<IActionResult> CreateStudent()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateStudent(CreateStudentViewModel createStudentViewModel)
        {
            var result = await _studentService.InsertAsync(createStudentViewModel);

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> UpdateStudentIdentity(int id)
        {
            var studentIdentity = await _studentService.GetStudentIdentityByIdAsync(id);

            return PartialView(studentIdentity);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateStudentIdentity(StudentIdentityViewModel studentIdentityViewModel)
        {
            var result = await _studentService.UpdateStudentIdentityAsync(studentIdentityViewModel);

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> UpdateContactInformation(int id)
        {
            var contactInformation = await _studentService.GetContactInformationByIdAsync(id);

            return PartialView(contactInformation);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateContactInformation(ContactInformationViewModel contactInformationViewModel)
        {
            var result = await _studentService.UpdateContactInformationAsync(contactInformationViewModel);

            return RedirectToAction(nameof(Index));
        }
    }
}

Presentations/Atilim.Presentations.WebApplication/Views/Students/CreateStudent.cshtml
@model Atilim.Presentations.WebApplication.ViewModels.StudentViewModels.CreateStudentViewModel

@{
    ViewData["Title"] = "CreateStudent";
}

<h1>Create Student</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Students" asp-action="CreateStudent" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label asp-for="StudentNo" class="control-label"></label>
                        <input asp-for="StudentNo" class="form-control" />
                        <span asp-validation-for="StudentNo" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="StudentItentity.TCIdentificationNo" class="control-label"></label>
                        <input asp-for="StudentItentity.TCIdentificationNo" class="form-control" />
                        <span asp-validation-for="StudentItentity.TCIdentificationNo" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="StudentItentity.Name" class="control-label"></label>
                        <input asp-for="StudentItentity.Name" class="form-control" />
                        <span asp-validation-for="StudentItentity.Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="StudentItentity.Surname" class="control-label"></label>
                        <input asp-for="StudentItentity.Surname" class="form-control" />
                        <span asp-validation-for="StudentItentity.Surname" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="StudentItentity.CityOfBirth" class="control-label"></label>
                        <input asp-for="StudentItentity.CityOfBirth" class="form-control" />
                        <span asp-validation-for="StudentItentity.CityOfBirth" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="StudentItentity.DateOfBirth" class="control-label"></label>
                        <input asp-for="StudentItentity.DateOfBirth" class="form-control" />
                        <span asp-validation-for="StudentItentity.DateOfBirth" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="ContactInformation.Address" class="control-label"></label>
                        <input asp-for="ContactInformation.Address" class="form-control" />
                        <span asp-validation-for="ContactInformation.Address" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ContactInformation.Country" class="control-label"></label>
                        <input asp-for="ContactInformation.Country" class="form-control" />
                        <span asp-validation-for="ContactInformation.Country" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ContactInformation.City" class="control-label"></label>
                        <input asp-for="ContactInformation.City" class="form-control" />
                        <span asp-validation-for="ContactInformation.City" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ContactInformation.District" class="control-label"></label>
                        <input asp-for="ContactInformation.District" class="form-control" />
                        <span asp-validation-for="ContactInformation.District" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ContactInformation.Email" class="control-label"></label>
                        <input asp-for="ContactInformation.Email" class="form-control" />
                        <span asp-validation-for="ContactInformation.Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ContactInformation.MobilePhoneNumber" class="control-label"></label>
                        <input asp-for="ContactInformation.MobilePhoneNumber" class="form-control" />
                        <span asp-validation-for="ContactInformation.MobilePhoneNumber" class="text-danger"></span>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Presentations/Atilim.Presentations.WebApplication/Views/Students/GetStudentOtherInfosById.cshtml
@model StudentViewModel

<div class="row">
    <div class="col-md-6">
        <table class="table table striped">
            <caption class="font-weight-bold">Student Identity</caption>
            <thead>
                <tr>
                    <th>TCIdentificationNo </th>
                    <th>Name </th>
                    <th>Surname </th>
                    <th>CityOfBirth </th>
                    <th>DateOfBirth </th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>@Model.StudentIdentity.TCIdentificationNo </td>
                    <td>@Model.StudentIdentity.Name </td>
                    <td>@Model.StudentIdentity.Surname </td>
                    <td>@Model.StudentIdentity.CityOfBirth </td>
                    <td>@Model.StudentIdentity.DateOfBirth </td>
                    <td>
                        <button id="student-identity-update-button" type="button" class="btn btn-primary" data-id="" data-toggle="modal" data-target="#student-edit-modal" onclick="update_button(this, @Model.StudentIdentity.Id, @Model.Id, 'Students', 'UpdateStudentIdentity')">
                            <i class="fa-solid fa-pen-to-square"></i>
                        </button>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="col-md-6">
        <table class="table table striped">
            <caption class="font-weight-bold">Contact Information</caption>
            <thead>
                <tr>
                    <th>Address </th>
                    <th>Country </th>
                    <th>City </th>
                    <th>District </th>
                    <th>Email </th>
                    <th>MobilePhoneNumber</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>@Model.ContactInformation.Address</td>
                    <td>@Model.ContactInformation.Country</td>
                    <td>@Model.ContactInformation.City</td>
                    <td>@Model.ContactInformation.District</td>
                    <td>@Model.ContactInformation.Email</td>
                    <td>@Model.ContactInformation.MobilePhoneNumber </td>
                    <td>
                        <button id="contact-information-update-button" type="button" class="btn btn-primary" data-toggle="modal" data-target="#student-edit-modal" onclick="update_button(this, @Model.ContactInformation.Id, @Model.Id, 'Students', 'UpdateContactInformation')">
                            <i class="fa-solid fa-pen-to-square"></i>
                        </button>
                    </td>
                </tr>
            </tbody>
        </table>

    </div>
    <div class="col-md-6">
        <table class="table table-striped">
            <caption class="font-weight-bold">
                Curriculum && Lesson
            </caption>
            <thead>
                <tr>
                    <th>CurriculumName</th>
                    <th>Lessons</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>@Model.Curriculum.CurriculumName</td>
                    <td>
                        <a class="btn btn-dark w-50" data-toggle="collapse" href="#lesson-collapse-@Model.Curriculum.Id" role="button" aria-expanded="false" aria-controls="lesson-collapse-@Model.Curriculum.Id">
                            Lesson Count: @Model.Curriculum.CurriculumLessons.Count()
                        </a>
                    </td>
                    <td>
                        <a asp-controller="Curriculums" asp-action="Update" asp-route-id="@Model.Curriculum.Id" class="btn btn-primary"><i class="fa-solid fa-pen-to-square"></i></a>
                    </td>
                </tr>
                <tr>
                    <td class="collapse" id="lesson-collapse-@Model.Curriculum.Id" colspan="5">
                        <div class="card card-body">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>LessonName</th>
                                        <th>LessonCode</th>
                                        <th>Status</th>
                                        <th>Credit</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var curriculumLesson in Model.Curriculum.CurriculumLessons)
                                    {
                                        <tr>
                                            <td>@curriculumLesson.Lesson.Id</td>
                                            <td>@curriculumLesson.Lesson.LessonName</td>
                                            <td>@curriculumLesson.Lesson.LessonCode</td>
                                            <td>@curriculumLesson.Lesson.Status</td>
                                            <td>@curriculumLesson.Lesson.Credit</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

Presentations/Atilim.Presentations.WebApplication/Views/Students/Index.cshtml
@model List<StudentViewModel>

<style>
    .active {
        color: black !important;
        background-color: darkgrey !important;
        border: 1px dashed black !important;
    }

    button p {
        margin-bottom: 5px !important;
        text-align: left !important;
    }
</style>

<div class="col-md-12 mb-2">
    <h4>Students</h4>
    <a asp-controller="Students" asp-action="CreateStudent" class="btn btn-success">
        <i class="fa-solid fa-plus-minus"></i>
    </a>
</div>

<div class="col-md-3">
    <div class="row">
        <div class="col-md-12 student-base-info">
            @foreach (var student in Model)
            {
                <button class="btn btn-dark text-white w-100 mb-2" onclick="on_click_load_student_infos(this,Number('@student.Id'))">
                    <div class="row">
                        <div class="col-md-12">
                            <p class="w-100">
                                <span>Id :</span>
                                <span>@student.Id</span>
                            </p>
                        </div>
                        <div class="col-md-12">
                            <p>
                                <strong>Full Name :</strong>
                                <span>@student.FullName</span>
                            </p>
                        </div>
                        <div class="col-md-12">
                            <p>
                                <strong>Curriculum :</strong>
                                <span>@(student.Curriculum is null ? "-" : student.Curriculum.CurriculumName)</span>
                            </p>
                        </div>
                    </div>
                </button>
            }
        </div>
    </div>
</div>
<div class="col-md-9 student-info-section">
</div>

<div class="modal fade" id="student-edit-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Update Modal</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
            </div>
            @* <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div> *@
        </div>
    </div>
</div>

@section Scripts{

    <script>
        function update_button(e, id, studentId, controllerName, actionName)
        {
            $('#student-edit-modal').modal('show');
            $('#student-edit-modal .modal-body').empty();

            $.get(`/${controllerName}/${actionName}`, { id }, (result) =>
            {
                $('#student-edit-modal .modal-body').html(result);

            });
        }

        function on_click_load_student_infos(e, studentId)
        {
            $('.student-base-info button').removeClass("active");

            $(e).addClass('active');

            $.get('/Students/GetStudentOtherInfosById', { studentId }, (result) =>
            {
                $('.student-info-section').empty();
                $('.student-info-section').html(result);
            });
        }
    </script>
}

Presentations/Atilim.Presentations.WebApplication/Views/Students/UpdateContactInformation.cshtml
@model Atilim.Presentations.WebApplication.ViewModels.StudentViewModels.ContactInformationViewModel

<h4>Contact Information</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-controller="Students" asp-action="UpdateContactInformation">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input asp-for="StudentIdentityId" type="hidden" />
            <input asp-for="Id" class="form-control" type="hidden" />
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="District" class="control-label"></label>
                <input asp-for="District" class="form-control" />
                <span asp-validation-for="District" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MobilePhoneNumber" class="control-label"></label>
                <input asp-for="MobilePhoneNumber" class="form-control" />
                <span asp-validation-for="MobilePhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />

                <a asp-action="Index">Back to List</a>
            </div>
        </form>
    </div>
</div>

Presentations/Atilim.Presentations.WebApplication/Views/Students/UpdateStudentIdentity.cshtml
@model Atilim.Presentations.WebApplication.ViewModels.StudentViewModels.StudentIdentityViewModel

<h4>Student Identity</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-controller="Students" asp-action="UpdateStudentIdentity" method="post">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input asp-for="Id" class="form-control" type="hidden" />
            <input asp-for="StudentId" class="form-control" type="hidden" />
            <input asp-for="UserId" class="form-control" type="hidden" />

            <div class="form-group">
                <label asp-for="TCIdentificationNo" class="control-label"></label>
                <input asp-for="TCIdentificationNo" class="form-control" />
                <span asp-validation-for="TCIdentificationNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CityOfBirth" class="control-label"></label>
                <input asp-for="CityOfBirth" class="form-control" />
                <span asp-validation-for="CityOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfBirth" class="control-label"></label>
                <input asp-for="DateOfBirth" class="form-control" />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a asp-action="Index">Back to List</a>
            </div>
        </form>
    </div>
</div>